### ISSUE TITLE
Add registry auditing property to xAdcsCertificationAuthority resource

### ISSUE THREAD

**Issue by megamorf** [PowerShell/ActiveDirectoryCSDsc#4]
Hey guys,

The following Microsoft PKI white paper http://aka.ms/securingpkidl recommends enabling additional reg key auditing for changes to CA specific reg keys (page 77). I can add that to the xAdcsCertificationAuthority resource if you're fine with that.

**Comment by PlagueHO** [comment]
I can't speak for anyone else, but I'd actually be really interested in seeing a DSC resource that allows control of all of the CA registry settings that are provided by the certutil -setreg command.

For example, when setting up a PKI from scratch you've usually got to configure things like the AIA addresses and CDP addresses, default certificate validity as well as the AuditFilter flags you're talking about here.

At the moment I do all this post CA config using the Script resource - and it is nasty (see https://github.com/PlagueHO/LabBuilder/blob/master/LabBuilder/DSCLibrary/STANDALONE_ROOTCA.DSC.ps1#L90).

I'd love it the resource could be extended (or a new ADCSAdvancedConfig created) that covered all these advanced settings. After all, in the test lab guides from Microsoft (https://technet.microsoft.com/en-us/library/cc772393%28v=ws.10%29.aspx) all of these settings need to be configured. :smile:

So that's my wishlist on this one. That being said, I'd be happy with any of the settings being implemented :+1:
